# Generated by Django 2.0.1 on 2018-06-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetoutput', '0002_credetialsmodel_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
