# Generated by Django 2.0.1 on 2018-06-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheetoutput', '0003_sheetmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheetmodel',
            old_name='url',
            new_name='sheetID',
        ),
    ]
